apiVersion: apps/v1
kind: Deployment
metadata:
  name: darknet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darknet
  template:
    metadata:
      labels:
        app: darknet
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: darknet
          image: gcr.io/teknoir/darknet:arm64v8
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: HMQ_SERVICE_HOST
              value: "hmq.kube-system"
            - name: HMQ_SERVICE_PORT
              value: "1883"
            - name: MQTT_IN_0
              value: "darknet/in"
            - name: MQTT_OUT_0
              value: "darknet/out"
            - name: NAMES_FILE
              value: "/darknet/coco.names"
            - name: CFG_FILE
              value: "/darknet/yolov3.cfg"
            - name: WEIGHTS_FILE
              value: "/darknet/yolov3.weights"
